trigger:
  branches:
    include:
    - gh-pages

resources:
  repositories:
  - repository: templates
    type: git
    name: 'ENG - Standard/ENG - Standard'
    ref: 'refs/heads/debug/minio'
variables:
- group: 'mfe-var-group'
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- stage: Prepare
  jobs:
  - job: Read
    displayName: 'Checkout latest version'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        LATEST_VERSION=$(readlink latest)
        echo "##vso[task.setvariable variable=latestVersion]$LATEST_VERSION"
        echo "$LATEST_VERSION"
        # Update build number
        echo "##vso[build.updatebuildnumber]$LATEST_VERSION"
      displayName: 'Read latest version'
      name: printvar

    #upload to artifact
    - publish: $(System.DefaultWorkingDirectory)/$(latestVersion)
      artifact: latest

- template: templates/deploy/minio.yml@templates
  parameters:
    dependsOn: 'Prepare'
    environment: 'Minio_Collaudo'
    minioEndpoint: '$(MINIOENDPOINTCOLLAUDO)'
    minioUsername: '$(MINIOUSERCOLLAUDO)'
    minioPassword: '$(MINIOPASSCOLLAUDO)'
    bucket: 'servicesDocs'
    deleteBeforeUpload: 'true'
    folder: 'latest'
